/**
 * Cloudflare Pages Function to handle software request submissions
 * Creates GitHub issues automatically via GitHub API
 */

interface RequestBody {
  softwareName: string;
  additionalInfo?: string;
  language: 'zh-CN' | 'en';
}

interface Env {
  GITHUB_TOKEN: string;
}

export const onRequestPost: PagesFunction<Env> = async (context) => {
  const { request, env } = context;

  // CORS headers - restrict to actual domain in production
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*', // TODO: Replace with actual domain in production
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  };

  // Handle CORS preflight
  if (request.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Parse request body
    let body: RequestBody;
    try {
      body = await request.json() as RequestBody;
    } catch (parseError) {
      return new Response(
        JSON.stringify({ 
          error: 'Invalid request format' 
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    
    // Validate input
    if (!body.softwareName || body.softwareName.trim().length === 0) {
      return new Response(
        JSON.stringify({ 
          error: body.language === 'en' 
            ? 'Software name is required' 
            : '软件名称不能为空' 
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Validate software name length (GitHub title limit is 256)
    if (body.softwareName.length > 200) {
      return new Response(
        JSON.stringify({ 
          error: body.language === 'en' 
            ? 'Software name is too long (maximum 200 characters)' 
            : '软件名称过长（最多 200 个字符）' 
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Validate additional info length
    if (body.additionalInfo && body.additionalInfo.length > 5000) {
      return new Response(
        JSON.stringify({ 
          error: body.language === 'en' 
            ? 'Additional information is too long (maximum 5000 characters)' 
            : '补充说明过长（最多 5000 个字符）' 
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Validate language
    const isEnglish = body.language === 'en';
    if (body.language && body.language !== 'en' && body.language !== 'zh-CN') {
      return new Response(
        JSON.stringify({ 
          error: 'Invalid language parameter' 
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Check for GitHub token
    if (!env.GITHUB_TOKEN) {
      console.error('GITHUB_TOKEN environment variable is not set');
      return new Response(
        JSON.stringify({ 
          error: body.language === 'en'
            ? 'Server configuration error. Please contact administrator.'
            : '服务器配置错误，请联系管理员。'
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const isEnglish = body.language === 'en';
    
    // Prepare issue title and body
    const issueTitle = isEnglish 
      ? `[Software Request] ${body.softwareName}`
      : `[软件申请] ${body.softwareName}`;
    
    const issueBody = isEnglish 
      ? `## Software Information

**Software Name**: ${body.softwareName}

${body.additionalInfo ? `**Additional Information**: ${body.additionalInfo}` : ''}

---

> This request was automatically generated by a user through the website request form.
> 
> **Processing Workflow**:
> 1. ✅ Request submitted
> 2. 🤖 Waiting for GitHub Copilot Agent to automatically search for software information
> 3. 📝 Agent will create resource files and descriptions following project rules
> 4. 👤 Waiting for admin review
> 5. 🎉 After approval, automatically published to the website

<!-- 
Label: software-request
Do not manually edit this Issue, it will be automatically processed by GitHub Actions.
-->
`
      : `## 软件信息

**软件名称**: ${body.softwareName}

${body.additionalInfo ? `**补充说明**: ${body.additionalInfo}` : ''}

---

> 此申请由用户通过网站申请表单自动生成。
> 
> **处理流程**:
> 1. ✅ 申请已提交
> 2. 🤖 等待 GitHub Copilot Agent 自动搜索软件信息
> 3. 📝 Agent 将按照项目规则创建资源文件和描述
> 4. 👤 等待管理员审核
> 5. 🎉 审核通过后自动发布到网站

<!-- 
标签: software-request
不要手动编辑此 Issue，它将由 GitHub Actions 自动处理。
-->
`;

    // Create GitHub issue
    const response = await fetch('https://api.github.com/repos/gmij/soft/issues', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'Cloudflare-Pages-Function'
      },
      body: JSON.stringify({
        title: issueTitle,
        body: issueBody,
        labels: ['software-request']
      })
    });

    if (!response.ok) {
      const errorData = await response.text();
      console.error('GitHub API error:', response.status, errorData);
      
      return new Response(
        JSON.stringify({ 
          error: body.language === 'en'
            ? 'Failed to create issue. Please try again later or create an issue directly on GitHub.'
            : '创建 Issue 失败，请稍后重试或直接在 GitHub 上创建 Issue。'
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const issueData = await response.json() as { number?: number; html_url?: string };

    // Validate response structure
    if (!issueData.number || !issueData.html_url) {
      console.error('Invalid GitHub API response:', issueData);
      return new Response(
        JSON.stringify({ 
          error: body.language === 'en'
            ? 'Unexpected response from GitHub. Please try again later.'
            : '来自 GitHub 的响应异常，请稍后重试。'
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Return success response
    return new Response(
      JSON.stringify({
        success: true,
        issueNumber: issueData.number,
        issueUrl: issueData.html_url,
        message: body.language === 'en'
          ? 'Request submitted successfully! Our team will process it soon.'
          : '申请提交成功！我们的团队会尽快处理。'
      }),
      { 
        status: 200, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );

  } catch (error) {
    console.error('Error processing request:', error);
    
    // Don't expose internal error details to client
    return new Response(
      JSON.stringify({ 
        error: 'Internal server error. Please try again later.'
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
};
